NethServer/nethserver-firewall-migration

- root/usr/share/nethesis/nethserver-firewall-migration/dhcp
Export DHCP config:
- max number of leases
- range configuration, even if disabled
- static leases with description field
See:
- https://openwrt.org/docs/guide-user/base-system/dhcp
- https://openwrt.org/docs/guide-user/base-system/dhcp_configuration
> dhcp: export global config and static leases

- root/usr/share/nethserver-firewall-migration/passwd
- ui/public/i18n/language.json
Export root password hash.
Password can be imported to avoid exposing migrated firewalls with a default weak password.
See also https://github.com/NethServer/nextsecurity/pull/65
> export: add root password

- root/usr/share/nethserver-firewall-migration/redirects
Avoid the use of ipset inside OpenWrt by generating a rule for each source IP:
Luci doesn't allow editing redirects using ipsets.
See also https://github.com/NethServer/nextsecurity/pull/94
> redirects: expand allow prop to multiple rules

- root/usr/share/nethserver-firewall-migration/redirects
Previously the hairpin configuration was missing
the list of zones where the reflection is active
See https://trello.com/c/h1deN8aq/76-hairpin-nat-from-multiple-zones
> redirects: configure hairpin zones

- root/usr/share/nethserver-firewall-migration/dhcp
Preserve NS7 behavior on migration
Card: https://trello.com/c/3Ar8d8mL/127-dns-dhcp-rebind-protection-management
> dhcp: disable rebind protection

- nethserver-firewall-migration.spec
- root/usr/sbin/firewall-migrate
The export.tar.gz is copied to the rom:
every time the factory reset is executed,
the migration will be restarted on first boot
> spec&script: generate squahfs image

- root/usr/share/nethserver-firewall-migration/reverse_proxy
It seems that this is the only field where the description is actually set. Feel free to correct me if I'm wrong.
Refs: NethServer/nethsecurity#227
> fix: updated name of description field

- root/usr/share/nethserver-firewall-migration/dhcp
DHCP range start should be an offset from the base network address, not am IP address (still allowed, probably going away in a future release).
> dhcp: start as offset from network address

- root/usr/sbin/firewall-migrate
Let's try to empty the disk buffer
> firewall-migrate: drop cache before reboot

- root/usr/share/nethserver-firewall-migration/rules
If a group object is used as source or destination, the IPs are listed in a single element separated by a comma. This commit make sure the converted source and destination are array of IP addresses.
https://github.com/NethServer/nethsecurity/issues/429
> rules: explode src and dest addresses

- root/usr/share/nethserver-firewall-migration/ipsec
While current values were good to establish a tunnel, the UI did not display them correctly.
Remap to equivalent values that are visible inside the UI.
NethServer/nethsecurity#429
> ipsec: remap hash_algorithm and salifetime

- root/usr/share/nethserver-firewall-migration/ipsec
Allow configuration of tunnels with multiple local and remote subnets.
See also:
- https://github.com/NethServer/nethsecurity/pull/442
- https://github.com/NethServer/nethsecurity/issues/449
> ipsec: generate multiple tunnel children

- root/usr/share/nethserver-firewall-migration/rules
Convert blue and orange zones to the new name to avoid errors like:
Section ns_93_udp (93_migrated_udp) option 'src' specifies invalid value 'blue'
NethServer/nethsecurity#726
> rules: fix blue and orange zones

- root/usr/share/nethserver-firewall-migration/openvpn
Users migrated from NS6 to NS7 do not have the status prop. If the status prop is not present, just assume the user is enabled: this should be the same behavior of the OpenVPN authentication process.
> openvpn: do not ignore users without 'status' prop

- root/usr/sbin/firewall-migrate
Writing the system image immediately after the read-only remount could lead to kernel corruption and boot failure (XZ compressed data is corrupt). Waiting one second between remount and write avoids the problem.
> firewall-migrate: sleep before image write

- root/usr/share/nethserver-firewall-migration/redirects
Changes:
- fix naming of vpn zones
- add OpenVPN RW zone only if server is enabled
- add OpenVPN tunnel zone only if there is at least one tunnel enabled
- add IPsec tunnel zone only if there is at least one tunnel enabled
NethServer/nethsecurity#787
> redirects: fix VPN reflection zones

- root/usr/share/nethserver-firewall-migration/rules
Custom zones are not created inside NS8.
As a consquence, a rule with a custom zone is ignored by fw4.
Remove the custom zone and use the any zone.
NethServer/nethsecurity#789
> rules: ignore custom zones

- root/usr/share/nethserver-firewall-migration/openvpn
The cn was not parsed correctly if it was containing a space and dot inside the company field.
Example:
/C=--/ST=SomeState/L=Hometown/O=E.bad Test/CN=mario1/emailAddress=admin@test.gs.nethserver.net
NethServer/nethsecurity#794
> openvpn: fix certificate export

- root/usr/share/nethserver-firewall-migration/ssh
The documentation states to use use 1 and 0, but LuCI and NS UI use on and off
NethServer/nethsecurity#806
> ssh: change values to on/off

- root/usr/share/nethserver-firewall-migration/openvpn_tunnels
Skip tunnels that does not have a valid configuration file: they will produce a bad export that can't be imported.
NethServer/nethsecurity#889
> fix(openvpn_tunnel): do not export invalid tunnels

- root/usr/sbin/firewall-migrate
drop_caches reclaims RAM, but the OOM Killer will do the right job.
reboot may fail, the sysrq-trigger is safer.
> migrate: do not drop caches

- root/usr/share/nethserver-firewall-migration/network
By removing the usage of the nslabel, the following issues will be fixed:
- make sure the name of the interface does not execeed 15 chars
- avoid naming collisions when first chars 15 are the same
NethServer/nethsecurity#1067
> fix(network): do not use label for wans
