NethServer/nethserver-firewall-migration

root/usr/share/nethserver-firewall-migration/network

network: export PPPoE config

---

root/usr/share/nethserver-firewall-migration/network

https://trello.com/c/kaBRn0ES/38-network-migration-bridges-and-bonds

network: export bridges and bonds

---

root/usr/share/nethserver-firewall-migration/ipsec

Export IPSec tunnel configuration

export: add ipsec tunnels

---

root/usr/share/nethserver-firewall-migration/flashstart

Export Flashstart configuration

export: add Flashstart

---

README.rst
nethserver-firewall-migration.spec
root/usr/sbin/firewall-migrate

In-place upgrade

---

root/usr/share/nethserver-firewall-migration/acme
root/usr/share/nethserver-firewall-migration/reverse_proxy
ui/public/i18n/language.json

Export configuration for reverse proxies:
- simple and host-based reverse proxies
- Let's Encrypt certificates

Reverse proxy

---

root/usr/share/nethserver-firewall-migration/openvpn

Export VPN user password if LDAP is installed locally. Hashed password can be used for authentication using mkpasswd command.

ovpn: export user passwords

---

root/usr/share/nethserver-firewall-migration/reverse_proxy

See https://trello.com/c/RfTnoD6O/78-nginx-proxypass-not-starting-at-boot

reverse proxy: add DNS hack

---

root/usr/share/nethserver-firewall-migration/threat_shield

https://trello.com/c/NT5xCtYa/85-switch-from-ts-ip-to-banip

threat_shield: move to banip implementation

---

root/usr/share/nethserver-firewall-migration/openvpn_tunnels

Card: https://trello.com/c/oM24VF2z/164-fix-openvpn-tunnel-migration
See also https://github.com/NethServer/nethsecurity/pull/203
TODO:

Fix OpenVPN tunnels migration

---

root/usr/share/nethserver-firewall-migration/hotspot

Card: https://trello.com/c/7u0ZdJgn/249-hotspot-migration-refactor

hotspot: refactor for new config

---

root/usr/share/nethserver-firewall-migration/rules

Card: https://trello.com/c/Qd0QkDLf/179-firewall-rules

rules: fix vpn zones, add missing fields

---

root/usr/share/nethserver-firewall-migration/reverse_proxy

Card: https://github.com/NethServer/python3-nethsec/pull/28

removed unused entries from reverse proxy migration tool

---

root/usr/share/nethserver-firewall-migration/openvpn

Make sure to use local database with no account
provider is installed
NethServer/nethsecurity#559

opnvpn: fix local db export

---

root/usr/share/nethserver-firewall-migration/rules

Changes:
- matches both 'any' and 'any+' values
- forse ns_service any value
NethServer/nethsecurity#727

rules: fix migration of any service

---

root/usr/share/nethserver-firewall-migration/rules

Changes:
- fix IPsec zone name
- map OpenVPN zones to `*`
NethServer/nethsecurity#788

rules: fix IPsec and OpenVPN zones

---

root/usr/share/nethserver-firewall-migration/dhcp
root/usr/share/nethserver-firewall-migration/redirects

Fixing issue with domain import of DHCP, also fixed configuration generation if there are no OpenVPN configured.
Ref:
- https://github.com/NethServer/nethsecurity/issues/857

Migration fixes

---

root/usr/share/nethserver-firewall-migration/dhcp

Ref:
- https://github.com/NethServer/nethsecurity/issues/857

fix(dhcp): adding back domain field but emptying it out

---

ui/src/views/Dashboard.vue

Remove unnecessary (and potentially dangerous) v-html usages.
v-html security note: https://vuejs.org/api/built-in-directives.html#v-html

fix: remove v-html usage

---

root/usr/share/nethserver-firewall-migration/network

network: fix zone for PPPoE aliases
